import {
  Settings,
  Layers,
  Send,
  UserPlus,
  CreditCard,
  FileText,
  DollarSign,
  Globe,
  Tag,
  ChevronRight,
  Home,
  Server,
  Users,
  UserCheck,
  Map,
  Grid,
  Wifi,
  Box,
  LifeBuoy,
  MessageCircle,
  Circle, // <- ini untuk child menu "dot"
} from "lucide-react";

export const icons = {
  settings: Settings,
  layers: Layers,
  send: Send,
  "user-plus": UserPlus,
  "credit-card": CreditCard,
  "file-text": FileText,
  "dollar-sign": DollarSign,
  globe: Globe,
  tag: Tag,
  chevron: ChevronRight, // untuk parent menu
  home: Home,
  server: Server,
  users: Users,
  "user-check": UserCheck,
  map: Map,
  grid: Grid,
  wifi: Wifi,
  box: Box,
  "life-buoy": LifeBuoy,
  "message-circle": MessageCircle,
  dot: Circle, // <- icon titik besar untuk child menu
};
